---

- include: get-cert-cn.yml
  when: TLS_DEST_BASENAME is undefined

- name: Certificate files copied to target
  tags: [certs-copied]
  copy:
    src: "{{ item.src_path }}"
    dest: "{{ item.dest_path }}"
  with_items:
    - src_path: "{{ TLS_PRIVKEY_SRC_FILE }}"
      dest_path: "{{ TLS_PRIVKEY_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.key"
    - src_path: "{{ TLS_CERT_SRC_FILE }}"
      dest_path: "{{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.crt"
    - src_path: "{{ TLS_CACHAIN_SRC_FILE }}"
      dest_path: "{{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.cachain.crt"

- name: Full certificate chain created
  shell: >
    cat {{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.crt
    {{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.cachain.crt >>
    {{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.fullchain.crt
  args:
    creates: "{{ TLS_CERT_DEST_DIR }}/{{ TLS_DEST_BASENAME }}.fullchain.crt"
